version: '3'
services: 
  ui: 
    build: 
      context: ./ui
    container_name: ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-ui
    ports: 
      - "8080:8080"
  nginx: 
    container_name: nginx
    depends_on: 
      - ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx
    ports: 
      - "80:80"
    build:
      context: ./nginx