version: '3'
services: 
  ui: 
    build: 
      context: ../ui
    container_name: ui
    ports: 
      - "8080:8080"
  nginx: 
    container_name: nginx
    depends_on: 
      - ui
    ports: 
      - "80:80"
    build:
      context: ../nginx